insert into Company (name) values ('Swift, Schinner and Russel');
insert into Company (name) values ('Farrell Group');
insert into Company (name) values ('Dietrich, Spencer and Pacocha');
insert into Company (name) values ('Hahn, Hills and Fritsch');
insert into Company (name) values ('Effertz-Labadie');
insert into Company (name) values ('Luettgen, Barrows and Mann');
insert into Company (name) values ('Kuphal and Sons');
insert into Company (name) values ('Frami, Strosin and Mayert');
insert into Company (name) values ('Nikolaus and Sons');
insert into Company (name) values ('Carter, Bednar and Heller');
insert into Company (name) values ('Thiel-Hamill');
insert into Company (name) values ('Toy-Graham');
insert into Company (name) values ('Smitham, Wiza and Erdman');
insert into Company (name) values ('Bins, Carroll and Gerlach');
insert into Company (name) values ('Treutel, Champlin and Harvey');
insert into Company (name) values ('Heaney, Abernathy and Schamberger');
insert into Company (name) values ('Donnelly, Schuster and Stoltenberg');
insert into Company (name) values ('Wilderman-Goodwin');
insert into Company (name) values ('West, McGlynn and Bauch');
insert into Company (name) values ('Raynor and Sons');
insert into Company (name) values ('Towne-Koch');
insert into Company (name) values ('Bailey-Jerde');
insert into Company (name) values ('Schulist-Nitzsche');
insert into Company (name) values ('Batz-Barton');
insert into Company (name) values ('Walter-Jacobi');
insert into Company (name) values ('Bahringer-Padberg');
insert into Company (name) values ('Bashirian-Nitzsche');
insert into Company (name) values ('Wunsch, Morissette and Douglas');
insert into Company (name) values ('Donnelly, Gulgowski and Labadie');
insert into Company (name) values ('Stroman, Huel and Rath');
insert into Company (name) values ('Bailey Inc');
insert into Company (name) values ('Ledner and Sons');
insert into Company (name) values ('Keeling, Tromp and Satterfield');
insert into Company (name) values ('Hackett-Bergnaum');
insert into Company (name) values ('Conroy-Hodkiewicz');
insert into Company (name) values ('Pfeffer-Davis');
insert into Company (name) values ('Aufderhar, Bergstrom and Bergnaum');
insert into Company (name) values ('Thiel LLC');
insert into Company (name) values ('Schroeder-Zulauf');
insert into Company (name) values ('Cruickshank, Beatty and Deckow');
insert into Company (name) values ('Champlin-Gerhold');
insert into Company (name) values ('Mante Inc');
insert into Company (name) values ('Ernser Inc');
insert into Company (name) values ('Erdman-Lehner');
insert into Company (name) values ('Bode Group');
insert into Company (name) values ('Lubowitz Inc');
insert into Company (name) values ('Morar, Weimann and Kassulke');
insert into Company (name) values ('Auer-Howell');
insert into Company (name) values ('Miller LLC');
insert into Company (name) values ('Barrows LLC');
insert into Company (name) values ('Fisher, King and Gislason');
insert into Company (name) values ('Reinger-Towne');
insert into Company (name) values ('Mann-Dickinson');
insert into Company (name) values ('Moore-Cole');
insert into Company (name) values ('Wintheiser LLC');
insert into Company (name) values ('Sauer, Ondricka and Gaylord');
insert into Company (name) values ('Grant-Kertzmann');
insert into Company (name) values ('Kemmer-Schmidt');
insert into Company (name) values ('Metz, Nader and Goodwin');
insert into Company (name) values ('Kuhic-Greenholt');
insert into Company (name) values ('Wuckert-Lind');
insert into Company (name) values ('Conn and Sons');
insert into Company (name) values ('Dietrich-Swift');
insert into Company (name) values ('Padberg-Shanahan');
insert into Company (name) values ('Lindgren-Schultz');
insert into Company (name) values ('Sawayn-Wilderman');
insert into Company (name) values ('Gaylord-Schneider');
insert into Company (name) values ('Quitzon, Schuppe and Kshlerin');
insert into Company (name) values ('Herzog-Koch');
insert into Company (name) values ('Hackett Group');
insert into Company (name) values ('Rempel Group');
insert into Company (name) values ('Blick and Sons');
insert into Company (name) values ('Harvey and Sons');
insert into Company (name) values ('Hills, Doyle and Herzog');
insert into Company (name) values ('Adams, Effertz and Lynch');
insert into Company (name) values ('Bartoletti-Volkman');
insert into Company (name) values ('Bosco-Kessler');
insert into Company (name) values ('Smitham, Heathcote and Prohaska');
insert into Company (name) values ('Wilkinson and Sons');
insert into Company (name) values ('Rath, Kreiger and Klocko');
insert into Company (name) values ('Kunze and Sons');
insert into Company (name) values ('Goldner-Weimann');
insert into Company (name) values ('Schinner, Wilderman and Bradtke');
insert into Company (name) values ('Ernser, West and Harvey');
insert into Company (name) values ('Rohan, Feest and Hahn');
insert into Company (name) values ('Bahringer Inc');
insert into Company (name) values ('Bosco and Sons');
insert into Company (name) values ('Olson-Nienow');
insert into Company (name) values ('Walker and Sons');
insert into Company (name) values ('Rath-Weber');
insert into Company (name) values ('Vandervort, Keebler and Lueilwitz');
insert into Company (name) values ('Boyle Group');
insert into Company (name) values ('Bednar Group');
insert into Company (name) values ('Vandervort-Simonis');
insert into Company (name) values ('Terry-Murazik');
insert into Company (name) values ('Robel and Sons');
insert into Company (name) values ('Gusikowski, Feest and West');
insert into Company (name) values ('Johnston-Kuphal');
insert into Company (name) values ('Bartoletti, Goodwin and Conroy');
insert into Company (name) values ('Schumm, Pagac and Nienow');
