insert into Position (positionName) values ('Sales Representative');
insert into Position (positionName) values ('Research Nurse');
insert into Position (positionName) values ('Developer II');
insert into Position (positionName) values ('Senior Quality Engineer');
insert into Position (positionName) values ('Assistant Professor');
insert into Position (positionName) values ('Internal Auditor');
insert into Position (positionName) values ('Database Administrator III');
insert into Position (positionName) values ('Financial Analyst');
insert into Position (positionName) values ('Payment Adjustment Coordinator');
insert into Position (positionName) values ('Media Manager I');
insert into Position (positionName) values ('Teacher');
insert into Position (positionName) values ('VP Product Management');
insert into Position (positionName) values ('Dental Hygienist');
insert into Position (positionName) values ('VP Accounting');
insert into Position (positionName) values ('VP Sales');
insert into Position (positionName) values ('Senior Quality Engineer');
insert into Position (positionName) values ('Electrical Engineer');
insert into Position (positionName) values ('Compensation Analyst');
insert into Position (positionName) values ('Senior Quality Engineer');
insert into Position (positionName) values ('Teacher');
insert into Position (positionName) values ('Technical Writer');
insert into Position (positionName) values ('Project Manager');
insert into Position (positionName) values ('Quality Control Specialist');
insert into Position (positionName) values ('Paralegal');
insert into Position (positionName) values ('Legal Assistant');
insert into Position (positionName) values ('Accounting Assistant I');
insert into Position (positionName) values ('Dental Hygienist');
insert into Position (positionName) values ('Civil Engineer');
insert into Position (positionName) values ('Technical Writer');
insert into Position (positionName) values ('Safety Technician II');
insert into Position (positionName) values ('Data Coordiator');
insert into Position (positionName) values ('Environmental Specialist');
insert into Position (positionName) values ('VP Product Management');
insert into Position (positionName) values ('Senior Quality Engineer');
insert into Position (positionName) values ('Cost Accountant');
insert into Position (positionName) values ('Librarian');
insert into Position (positionName) values ('VP Sales');
insert into Position (positionName) values ('Operator');
insert into Position (positionName) values ('Sales Associate');
insert into Position (positionName) values ('Structural Analysis Engineer');
insert into Position (positionName) values ('Food Chemist');
insert into Position (positionName) values ('Computer Systems Analyst III');
insert into Position (positionName) values ('Account Executive');
insert into Position (positionName) values ('Account Executive');
insert into Position (positionName) values ('Senior Cost Accountant');
insert into Position (positionName) values ('Legal Assistant');
insert into Position (positionName) values ('Engineer IV');
insert into Position (positionName) values ('Product Engineer');
insert into Position (positionName) values ('Database Administrator IV');
insert into Position (positionName) values ('Professor');
insert into Position (positionName) values ('Research Nurse');
insert into Position (positionName) values ('Occupational Therapist');
insert into Position (positionName) values ('Paralegal');
insert into Position (positionName) values ('VP Product Management');
insert into Position (positionName) values ('Project Manager');
insert into Position (positionName) values ('Director of Sales');
insert into Position (positionName) values ('Quality Control Specialist');
insert into Position (positionName) values ('Senior Developer');
insert into Position (positionName) values ('Accounting Assistant III');
insert into Position (positionName) values ('Operator');
insert into Position (positionName) values ('Accounting Assistant I');
insert into Position (positionName) values ('Account Representative III');
insert into Position (positionName) values ('Civil Engineer');
insert into Position (positionName) values ('Nurse Practicioner');
insert into Position (positionName) values ('Health Coach III');
insert into Position (positionName) values ('Dental Hygienist');
insert into Position (positionName) values ('Office Assistant III');
insert into Position (positionName) values ('Web Designer I');
insert into Position (positionName) values ('Geologist I');
insert into Position (positionName) values ('Clinical Specialist');
insert into Position (positionName) values ('Sales Associate');
insert into Position (positionName) values ('Web Designer II');
insert into Position (positionName) values ('Community Outreach Specialist');
insert into Position (positionName) values ('Clinical Specialist');
insert into Position (positionName) values ('Paralegal');
insert into Position (positionName) values ('Developer IV');
insert into Position (positionName) values ('Senior Quality Engineer');
insert into Position (positionName) values ('Computer Systems Analyst II');
insert into Position (positionName) values ('Geological Engineer');
insert into Position (positionName) values ('Chief Design Engineer');
insert into Position (positionName) values ('Software Test Engineer II');
insert into Position (positionName) values ('Assistant Manager');
insert into Position (positionName) values ('Accounting Assistant IV');
insert into Position (positionName) values ('Financial Analyst');
insert into Position (positionName) values ('VP Quality Control');
insert into Position (positionName) values ('Account Representative I');
insert into Position (positionName) values ('Recruiter');
insert into Position (positionName) values ('Research Assistant I');
insert into Position (positionName) values ('Food Chemist');
insert into Position (positionName) values ('Structural Analysis Engineer');
insert into Position (positionName) values ('Administrative Assistant IV');
insert into Position (positionName) values ('Systems Administrator I');
insert into Position (positionName) values ('Community Outreach Specialist');
insert into Position (positionName) values ('Computer Systems Analyst III');
insert into Position (positionName) values ('Senior Quality Engineer');
insert into Position (positionName) values ('Community Outreach Specialist');
insert into Position (positionName) values ('Budget/Accounting Analyst III');
insert into Position (positionName) values ('Actuary');
insert into Position (positionName) values ('Human Resources Assistant III');
insert into Position (positionName) values ('Sales Associate');
insert into Position (positionName) values ('Associate Professor');
insert into Position (positionName) values ('Data Coordiator');
insert into Position (positionName) values ('Marketing Manager');
insert into Position (positionName) values ('Systems Administrator I');
insert into Position (positionName) values ('Junior Executive');
insert into Position (positionName) values ('Account Representative IV');
insert into Position (positionName) values ('Account Coordinator');
insert into Position (positionName) values ('Assistant Manager');
insert into Position (positionName) values ('Junior Executive');
insert into Position (positionName) values ('Compensation Analyst');
insert into Position (positionName) values ('Editor');
insert into Position (positionName) values ('Senior Cost Accountant');
insert into Position (positionName) values ('Media Manager I');
insert into Position (positionName) values ('Office Assistant II');
insert into Position (positionName) values ('Quality Engineer');
insert into Position (positionName) values ('Safety Technician IV');
insert into Position (positionName) values ('Programmer Analyst III');
insert into Position (positionName) values ('Data Coordiator');
insert into Position (positionName) values ('Biostatistician I');
insert into Position (positionName) values ('Marketing Manager');
insert into Position (positionName) values ('Recruiter');
insert into Position (positionName) values ('Nuclear Power Engineer');
insert into Position (positionName) values ('Civil Engineer');
insert into Position (positionName) values ('Internal Auditor');
insert into Position (positionName) values ('Help Desk Operator');
insert into Position (positionName) values ('Accounting Assistant IV');
insert into Position (positionName) values ('Administrative Assistant III');
insert into Position (positionName) values ('Administrative Officer');
insert into Position (positionName) values ('Compensation Analyst');
insert into Position (positionName) values ('VP Marketing');
insert into Position (positionName) values ('Software Test Engineer I');
insert into Position (positionName) values ('Web Designer II');
insert into Position (positionName) values ('Pharmacist');
insert into Position (positionName) values ('Professor');
insert into Position (positionName) values ('Help Desk Operator');
insert into Position (positionName) values ('Structural Engineer');
insert into Position (positionName) values ('Safety Technician I');
insert into Position (positionName) values ('Senior Developer');
insert into Position (positionName) values ('Information Systems Manager');
insert into Position (positionName) values ('Environmental Specialist');
insert into Position (positionName) values ('Computer Systems Analyst I');
insert into Position (positionName) values ('Food Chemist');
insert into Position (positionName) values ('Account Coordinator');
insert into Position (positionName) values ('Professor');
insert into Position (positionName) values ('Web Developer I');
insert into Position (positionName) values ('Professor');
insert into Position (positionName) values ('Paralegal');
insert into Position (positionName) values ('Mechanical Systems Engineer');
insert into Position (positionName) values ('Senior Sales Associate');
insert into Position (positionName) values ('Database Administrator I');
insert into Position (positionName) values ('Staff Accountant I');
insert into Position (positionName) values ('Marketing Assistant');
insert into Position (positionName) values ('Data Coordiator');
insert into Position (positionName) values ('Product Engineer');
insert into Position (positionName) values ('Administrative Officer');
insert into Position (positionName) values ('Electrical Engineer');
insert into Position (positionName) values ('Editor');
insert into Position (positionName) values ('Speech Pathologist');
insert into Position (positionName) values ('Senior Sales Associate');
insert into Position (positionName) values ('Database Administrator I');
insert into Position (positionName) values ('Analyst Programmer');
insert into Position (positionName) values ('Assistant Manager');
insert into Position (positionName) values ('Programmer Analyst IV');
insert into Position (positionName) values ('Programmer III');
insert into Position (positionName) values ('Assistant Media Planner');
insert into Position (positionName) values ('Software Test Engineer II');
insert into Position (positionName) values ('Staff Scientist');
insert into Position (positionName) values ('VP Product Management');
insert into Position (positionName) values ('Nuclear Power Engineer');
insert into Position (positionName) values ('Human Resources Assistant II');
insert into Position (positionName) values ('Accountant I');
insert into Position (positionName) values ('VP Quality Control');
insert into Position (positionName) values ('Administrative Officer');
insert into Position (positionName) values ('Senior Quality Engineer');
insert into Position (positionName) values ('Structural Analysis Engineer');
insert into Position (positionName) values ('Project Manager');
insert into Position (positionName) values ('Staff Scientist');
insert into Position (positionName) values ('Sales Representative');
insert into Position (positionName) values ('Budget/Accounting Analyst II');
insert into Position (positionName) values ('Nuclear Power Engineer');
insert into Position (positionName) values ('Office Assistant I');
insert into Position (positionName) values ('General Manager');
insert into Position (positionName) values ('Speech Pathologist');
insert into Position (positionName) values ('Accountant III');
insert into Position (positionName) values ('Assistant Professor');
insert into Position (positionName) values ('VP Accounting');
insert into Position (positionName) values ('Analyst Programmer');
insert into Position (positionName) values ('Data Coordiator');
insert into Position (positionName) values ('Assistant Manager');
insert into Position (positionName) values ('Clinical Specialist');
insert into Position (positionName) values ('Help Desk Technician');
insert into Position (positionName) values ('Junior Executive');
insert into Position (positionName) values ('Marketing Assistant');
insert into Position (positionName) values ('Environmental Tech');
insert into Position (positionName) values ('Programmer Analyst IV');
insert into Position (positionName) values ('Help Desk Technician');
insert into Position (positionName) values ('VP Accounting');
insert into Position (positionName) values ('Librarian');
insert into Position (positionName) values ('Product Engineer');
insert into Position (positionName) values ('Professor');
